services:
  site-layout-app:
    container_name: site-layout-app
    build:
      context: ./
      dockerfile: Dockerfile

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    ports:
      - 8000:3000
